if(WIN32)
    set(SUB_DIR_LIBS ${CMAKE_BUILD_TYPE}/win64)
    set(SUB_DIR_LIBS_DEBUG Debug/win64)
    set(SUB_DIR_LIBS_RELEASE Release/win64)
    set(SUB_DIR_LIBS_RELEASE_ASAN_UBSAN Release_asan_ubsan/win64)

    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        if (NOT DEFINED ENV{LLVM_LIB})
            message(FATAL_ERROR "LLVM_LIB is not set")
        endif()
        link_directories("${LLVM_LIB}")

        set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")
        set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
        set(CMAKE_C_DEPENDS_USE_COMPILER FALSE)
        set(CMAKE_CXX_DEPENDS_USE_COMPILER FALSE)
    endif()
else()
    message("[${projectName}] Only Windows build is supported at the moment.")
    return()
endif()

message("[${projectName}] CMAKE_CXX_FLAGS: [${CMAKE_CXX_FLAGS}], ENABLE_ASAN_UBSAN: [${ENABLE_ASAN_UBSAN}]")